name = "opentermsarchive"
license = "EUPL"
licenselink = "https://github.com/OpenTermsArchive/docs/blob/master/LICENSE"
homepage = "https://opentermsarchive.org"
tags = []
features = []
min_version = "0.41.0"
