name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  test:
    uses: "OpenTermsArchive/docs/.github/workflows/test.yml@main"
  deploy:
    needs: [ test ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Set Hugo up
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.108.0'
          extended: true # Prevent error building site: POSTCSS: failed to transform, see https://gohugo.io/troubleshooting/faq/#i-get-this-feature-is-not-available-in-your-current-hugo-version

      - name: Clean public dir
        run: rm -rf public

      - name: Print Hugo info
        run: |
          echo "hugo env"
          hugo env
          echo "hugo config"
          hugo config

      - name: Build with Hugo
        run: hugo --minify

      - name: Print public files
        run: |
          cd public
          find . -print

      - name: Deploy ./public directory to the remote gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: docs.opentermsarchive.org
